{
 "title": "Debezium Oracle Connector",
 "description": "Monitoring Dashboard for Debezium Oracle connector. ",
 "tags": [
  "oracle",
  "debezium"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Oracle Node",
    "query": {
     "query": "debezium_metrics_QueueTotalCapacity"
    }
   },
   {
    "name": "instance",
    "label": "Connector Node",
    "query": {
     "query": "debezium_metrics_QueueTotalCapacity"
    }
   },
   {
    "name": "plugin",
    "label": "plugin",
    "query": {
     "query": "debezium_metrics_QueueTotalCapacity"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Streaming Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "General Info",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "options": {
      "content": "\n# Debezium Oracle Connector Metrics\n\nThe Debezium Oracle connector has three metric types:\n\n* snapshot metrics\n\n* streaming metrics\n\n* schema history metrics\n\nFor more detailed information about the metrics please visit the Debezium documentation page\n\n[Click here to visit](https://debezium.io/documentation/reference/stable/connectors/oracle.html#oracle-monitoring)\n\n\n\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Connected",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_Connected{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      }
     ]
    },
    {
     "title": "Number Of Committed Transactions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_NumberOfCommittedTransactions{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      }
     ]
    },
    {
     "title": "Number Of Active Transactions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_NumberOfActiveTransactions{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\r\n"
      }
     ]
    },
    {
     "title": "Number Of Rolled Back Transactions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_NumberOfRolledBackTransactions{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      }
     ]
    },
    {
     "title": "Number Of Oversized Transactions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_NumberOfOversizedTransactions{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\r\n"
      }
     ]
    },
    {
     "title": "Total Number Of Events Seen",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      }
     ]
    },
    {
     "title": "Total Processed Rows",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_TotalProcessedRows{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      }
     ]
    },
    {
     "title": "Queue Total Capacity",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_QueueTotalCapacity{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      }
     ]
    },
    {
     "title": "Milliseconds Since Last Event",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "debezium_metrics_MilliSecondsSinceLastEvent{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      }
     ]
    },
    {
     "title": "Number Of Events Filtered",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      }
     ]
    },
    {
     "title": "Log Mining Batch Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_BatchSize{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      }
     ]
    },
    {
     "title": "Queue Remaining Capacity",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "debezium_metrics_QueueRemainingCapacity{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      },
      {
       "expr": "debezium_metrics_QueueTotalCapacity{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lag From Source In Milliseconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "debezium_metrics_LagFromSourceInMilliseconds{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}"
      }
     ]
    },
    {
     "title": "Milliseconds Behind Source",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "debezium_metrics_MilliSecondsBehindSource{context=\"streaming\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Snapshot Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Table Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalTableCount{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Rows Scanned",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 2 },
   "targets": [
    {
     "expr": "last_over_time(debezium_metrics_RowsScanned{context=\"snapshot\", name=\"$name\", job=\"debezium\", plugin=\"$plugin\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotRunning{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Snapshot Aborted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotAborted{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Snapshot Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotCompleted{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Remaining Tables",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_RemainingTableCount{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Number Of Events Filtered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfEventsFiltered{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotDurationInSeconds{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Event",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\r\n"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    },
    {
     "expr": "debezium_metrics_QueueTotalCapacity{context=\"snapshot\", instance=\"$instance\", job=\"debezium\", name=\"$name\", plugin=\"$plugin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number Of Events Seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Number Of Erroneous Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfErroneousEvents{context=\"snapshot\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\r\n"
    }
   ]
  },
  {
   "title": "Schema History Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metric Title",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "options": {
    "content": "\n# Schema Changes Metrics\n\nFor detailed explanation for all the schema changes metrics: [Visit Debezium documentation](https://debezium.io/documentation/reference/stable/connectors/oracle.html#oracle-schema-history-metrics)\n\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Recovery Start Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_RecoveryStartTime{context=\"schema-history\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Applied Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastAppliedChange{context=\"schema-history\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Recovered Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastRecoveredChange{context=\"schema-history\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Changes Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_ChangesRecovered{context=\"schema-history\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  },
  {
   "title": "Changes Applied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_ChangesApplied{context=\"schema-history\",instance=\"$instance\",job=\"debezium\",name=\"$name\",plugin=\"$plugin\"}\t\r"
    }
   ]
  }
 ]
}