#!/usr/bin/env python3
"""
Script to add redis_rb (Ruby client) API mappings to command JSON files.
"""

import json
import os
from pathlib import Path

# Redis-rb method mappings: command_name -> ruby method definition
# Format: { "COMMAND": { "signature": "...", "params": [...], "returns": {...} } }
REDIS_RB_MAPPINGS = {
    # === STRINGS ===
    "GET": [{"signature": "get(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "String", "description": ""}}],
    "SET": [{"signature": "set(key, value, ex: nil, px: nil, exat: nil, pxat: nil, nx: nil, xx: nil, keepttl: nil, get: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "value", "type": "String", "description": ""}, {"name": "ex", "type": "Integer", "description": "Set the specified expire time, in seconds."}, {"name": "px", "type": "Integer", "description": "Set the specified expire time, in milliseconds."}, {"name": "exat", "type": "Integer", "description": "Set the specified Unix time at which the key will expire, in seconds."}, {"name": "pxat", "type": "Integer", "description": "Set the specified Unix time at which the key will expire, in milliseconds."}, {"name": "nx", "type": "Boolean", "description": "Only set the key if it does not already exist."}, {"name": "xx", "type": "Boolean", "description": "Only set the key if it already exists."}, {"name": "keepttl", "type": "Boolean", "description": "Retain the time to live associated with the key."}, {"name": "get", "type": "Boolean", "description": "Return the old string stored at key, or nil if key did not exist."}], "returns": {"type": "String, Boolean", "description": "\"OK\" or true, false if :nx => true or :xx => true"}}],
    "MGET": [{"signature": "mget(*keys)", "params": [{"name": "*keys", "type": "Array<String>", "description": ""}], "returns": {"type": "Array<String>", "description": "an array of values for the specified keys"}}],
    "MSET": [{"signature": "mset(*args)", "params": [{"name": "*args", "type": "Array<String>", "description": "array of keys and values"}], "returns": {"type": "String", "description": "\"OK\""}}],
    "MSETNX": [{"signature": "msetnx(*args)", "params": [{"name": "*args", "type": "Array<String>", "description": "array of keys and values"}], "returns": {"type": "Boolean", "description": "whether or not all values were set"}}],
    "APPEND": [{"signature": "append(key, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "value", "type": "String", "description": "value to append"}], "returns": {"type": "Integer", "description": "length of the string after appending"}}],
    "GETRANGE": [{"signature": "getrange(key, start, stop)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "start", "type": "Integer", "description": "zero-based start offset"}, {"name": "stop", "type": "Integer", "description": "zero-based end offset"}], "returns": {"type": "String", "description": ""}}],
    "SETRANGE": [{"signature": "setrange(key, offset, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "offset", "type": "Integer", "description": "byte offset"}, {"name": "value", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "length of the string after it was modified"}}],
    "STRLEN": [{"signature": "strlen(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "the length of the value stored in the key, or 0 if the key does not exist"}}],
    "INCR": [{"signature": "incr(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "value after incrementing it"}}],
    "INCRBY": [{"signature": "incrby(key, increment)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "increment", "type": "Integer", "description": ""}], "returns": {"type": "Integer", "description": "value after incrementing it"}}],
    "INCRBYFLOAT": [{"signature": "incrbyfloat(key, increment)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "increment", "type": "Float", "description": ""}], "returns": {"type": "Float", "description": "value after incrementing it"}}],
    "DECR": [{"signature": "decr(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "value after decrementing it"}}],
    "DECRBY": [{"signature": "decrby(key, decrement)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "decrement", "type": "Integer", "description": ""}], "returns": {"type": "Integer", "description": "value after decrementing it"}}],
    "SETEX": [{"signature": "setex(key, ttl, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "ttl", "type": "Integer", "description": ""}, {"name": "value", "type": "String", "description": ""}], "returns": {"type": "String", "description": "\"OK\""}}],
    "PSETEX": [{"signature": "psetex(key, ttl, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "ttl", "type": "Integer", "description": ""}, {"name": "value", "type": "String", "description": ""}], "returns": {"type": "String", "description": "\"OK\""}}],
    "SETNX": [{"signature": "setnx(key, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "value", "type": "String", "description": ""}], "returns": {"type": "Boolean", "description": "whether the key was set or not"}}],
    "GETSET": [{"signature": "getset(key, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "value", "type": "String", "description": "value to replace the current value with"}], "returns": {"type": "String", "description": "the old value stored in the key, or nil if the key did not exist"}}],
    "GETDEL": [{"signature": "getdel(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "String", "description": "the old value stored in the key, or nil if the key did not exist"}}],
    "GETEX": [{"signature": "getex(key, ex: nil, px: nil, exat: nil, pxat: nil, persist: false)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "ex", "type": "Integer", "description": "Set the specified expire time, in seconds."}, {"name": "px", "type": "Integer", "description": "Set the specified expire time, in milliseconds."}, {"name": "exat", "type": "Integer", "description": "Set the specified Unix time at which the key will expire, in seconds."}, {"name": "pxat", "type": "Integer", "description": "Set the specified Unix time at which the key will expire, in milliseconds."}, {"name": "persist", "type": "Boolean", "description": "Remove the time to live associated with the key."}], "returns": {"type": "String", "description": "The value of key, or nil when key does not exist."}}],

    # === KEYS ===
    "KEYS": [{"signature": "keys(pattern = \"*\")", "params": [{"name": "pattern", "type": "String", "description": ""}], "returns": {"type": "Array<String>", "description": ""}}],
    "SCAN": [{"signature": "scan(cursor, **options)", "params": [{"name": "cursor", "type": "String, Integer", "description": "the cursor of the iteration"}, {"name": "match", "type": "String", "description": "only return keys matching the pattern"}, {"name": "count", "type": "Integer", "description": "return count keys at most per iteration"}, {"name": "type", "type": "String", "description": "return keys only of the given type"}], "returns": {"type": "Array", "description": "the next cursor and all found keys"}}],
    "DEL": [{"signature": "del(*keys)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": ""}], "returns": {"type": "Integer", "description": "number of keys that were deleted"}}],
    "UNLINK": [{"signature": "unlink(*keys)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": ""}], "returns": {"type": "Integer", "description": "number of keys that were unlinked"}}],
    "EXISTS": [{"signature": "exists(*keys)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": ""}], "returns": {"type": "Integer", "description": ""}}],
    "EXPIRE": [{"signature": "expire(key, seconds, nx: nil, xx: nil, gt: nil, lt: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "seconds", "type": "Integer", "description": "time to live"}, {"name": "nx", "type": "Boolean", "description": "Set expiry only when the key has no expiry."}, {"name": "xx", "type": "Boolean", "description": "Set expiry only when the key has an existing expiry."}, {"name": "gt", "type": "Boolean", "description": "Set expiry only when the new expiry is greater than current one."}, {"name": "lt", "type": "Boolean", "description": "Set expiry only when the new expiry is less than current one."}], "returns": {"type": "Boolean", "description": "whether the timeout was set or not"}}],
    "EXPIREAT": [{"signature": "expireat(key, unix_time, nx: nil, xx: nil, gt: nil, lt: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "unix_time", "type": "Integer", "description": "expiry time specified as a UNIX timestamp"}, {"name": "nx", "type": "Boolean", "description": "Set expiry only when the key has no expiry."}, {"name": "xx", "type": "Boolean", "description": "Set expiry only when the key has an existing expiry."}, {"name": "gt", "type": "Boolean", "description": "Set expiry only when the new expiry is greater than current one."}, {"name": "lt", "type": "Boolean", "description": "Set expiry only when the new expiry is less than current one."}], "returns": {"type": "Boolean", "description": "whether the timeout was set or not"}}],
    "EXPIRETIME": [{"signature": "expiretime(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "expiry time specified as number of seconds from UNIX Epoch"}}],
    "PEXPIRE": [{"signature": "pexpire(key, milliseconds, nx: nil, xx: nil, gt: nil, lt: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "milliseconds", "type": "Integer", "description": "time to live"}, {"name": "nx", "type": "Boolean", "description": "Set expiry only when the key has no expiry."}, {"name": "xx", "type": "Boolean", "description": "Set expiry only when the key has an existing expiry."}, {"name": "gt", "type": "Boolean", "description": "Set expiry only when the new expiry is greater than current one."}, {"name": "lt", "type": "Boolean", "description": "Set expiry only when the new expiry is less than current one."}], "returns": {"type": "Boolean", "description": "whether the timeout was set or not"}}],
    "PEXPIREAT": [{"signature": "pexpireat(key, ms_unix_time, nx: nil, xx: nil, gt: nil, lt: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "ms_unix_time", "type": "Integer", "description": "expiry time specified as number of milliseconds from UNIX Epoch"}, {"name": "nx", "type": "Boolean", "description": "Set expiry only when the key has no expiry."}, {"name": "xx", "type": "Boolean", "description": "Set expiry only when the key has an existing expiry."}, {"name": "gt", "type": "Boolean", "description": "Set expiry only when the new expiry is greater than current one."}, {"name": "lt", "type": "Boolean", "description": "Set expiry only when the new expiry is less than current one."}], "returns": {"type": "Boolean", "description": "whether the timeout was set or not"}}],
    "PEXPIRETIME": [{"signature": "pexpiretime(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "expiry time specified as number of milliseconds from UNIX Epoch"}}],
    "TTL": [{"signature": "ttl(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "remaining time to live in seconds"}}],
    "PTTL": [{"signature": "pttl(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "remaining time to live in milliseconds"}}],
    "PERSIST": [{"signature": "persist(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Boolean", "description": "whether the timeout was removed or not"}}],
    "DUMP": [{"signature": "dump(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "String", "description": "serialized_value"}}],
    "RESTORE": [{"signature": "restore(key, ttl, serialized_value, replace: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "ttl", "type": "String", "description": ""}, {"name": "serialized_value", "type": "String", "description": ""}, {"name": "replace", "type": "Boolean", "description": "if false, raises an error if key already exists"}], "returns": {"type": "String", "description": "\"OK\""}}],
    "MIGRATE": [{"signature": "migrate(key, options)", "params": [{"name": "key", "type": "String, Array<String>", "description": ""}, {"name": "options", "type": "Hash", "description": "host, port, db, timeout, copy, replace"}], "returns": {"type": "String", "description": "\"OK\""}}],
    "MOVE": [{"signature": "move(key, db)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "db", "type": "Integer", "description": ""}], "returns": {"type": "Boolean", "description": "whether the key was moved or not"}}],
    "COPY": [{"signature": "copy(source, destination, db: nil, replace: false)", "params": [{"name": "source", "type": "String", "description": ""}, {"name": "destination", "type": "String", "description": ""}, {"name": "db", "type": "Integer", "description": ""}, {"name": "replace", "type": "Boolean", "description": "removes the destination key before copying value to it"}], "returns": {"type": "Boolean", "description": "whether the key was copied or not"}}],
    "RANDOMKEY": [{"signature": "randomkey", "params": [], "returns": {"type": "String", "description": ""}}],
    "RENAME": [{"signature": "rename(old_name, new_name)", "params": [{"name": "old_name", "type": "String", "description": ""}, {"name": "new_name", "type": "String", "description": ""}], "returns": {"type": "String", "description": "\"OK\""}}],
    "RENAMENX": [{"signature": "renamenx(old_name, new_name)", "params": [{"name": "old_name", "type": "String", "description": ""}, {"name": "new_name", "type": "String", "description": ""}], "returns": {"type": "Boolean", "description": "whether the key was renamed or not"}}],
    "SORT": [{"signature": "sort(key, by: nil, limit: nil, get: nil, order: nil, store: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "by", "type": "String", "description": "use external key to sort elements by"}, {"name": "limit", "type": "Array", "description": "[offset, count] skip offset elements, return max count elements"}, {"name": "get", "type": "String, Array<String>", "description": "keys to retrieve per element"}, {"name": "order", "type": "String", "description": "combination of ASC, DESC and optionally ALPHA"}, {"name": "store", "type": "String", "description": "key to store the result at"}], "returns": {"type": "Array<String>, Integer", "description": "array of elements or count when store is specified"}}],
    "TYPE": [{"signature": "type(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "String", "description": "string, list, set, zset, hash or none"}}],

    # === HASHES ===
    "HLEN": [{"signature": "hlen(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "number of fields in the hash"}}],
    "HSET": [{"signature": "hset(key, *attrs)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*attrs", "type": "Array<String>, Hash<String, String>", "description": "array or hash of fields and values"}], "returns": {"type": "Integer", "description": "The number of fields that were added to the hash"}}],
    "HSETNX": [{"signature": "hsetnx(key, field, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "field", "type": "String", "description": ""}, {"name": "value", "type": "String", "description": ""}], "returns": {"type": "Boolean", "description": "whether or not the field was added to the hash"}}],
    "HMSET": [{"signature": "hmset(key, *attrs)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*attrs", "type": "Array<String>", "description": "array of fields and values"}], "returns": {"type": "String", "description": "\"OK\""}}],
    "HGET": [{"signature": "hget(key, field)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "field", "type": "String", "description": ""}], "returns": {"type": "String", "description": ""}}],
    "HMGET": [{"signature": "hmget(key, *fields)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*fields", "type": "Array<String>", "description": "array of fields"}], "returns": {"type": "Array<String>", "description": "an array of values for the specified fields"}}],
    "HRANDFIELD": [{"signature": "hrandfield(key, count = nil, with_values: false)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "count", "type": "Integer", "description": ""}, {"name": "with_values", "type": "Boolean", "description": "include values in output"}], "returns": {"type": "nil, String, Array<String>, Array<[String, String]>", "description": ""}}],
    "HDEL": [{"signature": "hdel(key, *fields)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*fields", "type": "String, Array<String>", "description": ""}], "returns": {"type": "Integer", "description": "the number of fields that were removed from the hash"}}],
    "HEXISTS": [{"signature": "hexists(key, field)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "field", "type": "String", "description": ""}], "returns": {"type": "Boolean", "description": "whether or not the field exists in the hash"}}],
    "HINCRBY": [{"signature": "hincrby(key, field, increment)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "field", "type": "String", "description": ""}, {"name": "increment", "type": "Integer", "description": ""}], "returns": {"type": "Integer", "description": "value of the field after incrementing it"}}],
    "HINCRBYFLOAT": [{"signature": "hincrbyfloat(key, field, increment)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "field", "type": "String", "description": ""}, {"name": "increment", "type": "Float", "description": ""}], "returns": {"type": "Float", "description": "value of the field after incrementing it"}}],
    "HKEYS": [{"signature": "hkeys(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Array<String>", "description": ""}}],
    "HVALS": [{"signature": "hvals(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Array<String>", "description": ""}}],
    "HGETALL": [{"signature": "hgetall(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Hash<String, String>", "description": ""}}],
    "HSCAN": [{"signature": "hscan(key, cursor, **options)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "cursor", "type": "String, Integer", "description": "the cursor of the iteration"}, {"name": "match", "type": "String", "description": "only return keys matching the pattern"}, {"name": "count", "type": "Integer", "description": "return count keys at most per iteration"}, {"name": "novalues", "type": "Boolean", "description": "whether or not to include values in the output"}], "returns": {"type": "Array", "description": "the next cursor and all found keys"}}],
    "HEXPIRE": [{"signature": "hexpire(key, ttl, *fields)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "ttl", "type": "Integer", "description": ""}, {"name": "*fields", "type": "Array<String>", "description": ""}], "returns": {"type": "Array<Integer>", "description": "Feedback on if the fields have been updated"}}],
    "HTTL": [{"signature": "httl(key, *fields)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*fields", "type": "Array<String>", "description": ""}], "returns": {"type": "Array<Integer>", "description": "Feedback on the TTL of the fields"}}],
    "HPEXPIRE": [{"signature": "hpexpire(key, ttl, *fields, nx: nil, xx: nil, gt: nil, lt: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "ttl", "type": "Integer", "description": ""}, {"name": "*fields", "type": "Array<String>", "description": ""}, {"name": "nx", "type": "Boolean", "description": "Set expiry only when the key has no expiry."}, {"name": "xx", "type": "Boolean", "description": "Set expiry only when the key has an existing expiry."}, {"name": "gt", "type": "Boolean", "description": "Set expiry only when the new expiry is greater than current one."}, {"name": "lt", "type": "Boolean", "description": "Set expiry only when the new expiry is less than current one."}], "returns": {"type": "Array<Integer>", "description": "Feedback on if the fields have been updated"}}],
    "HPTTL": [{"signature": "hpttl(key, *fields)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*fields", "type": "Array<String>", "description": ""}], "returns": {"type": "Array<Integer>", "description": "Feedback on the TTL of the fields"}}],

    # === LISTS ===
    "LLEN": [{"signature": "llen(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": ""}}],
    "LMOVE": [{"signature": "lmove(source, destination, where_source, where_destination)", "params": [{"name": "source", "type": "String", "description": "source key"}, {"name": "destination", "type": "String", "description": "destination key"}, {"name": "where_source", "type": "String, Symbol", "description": "LEFT or RIGHT"}, {"name": "where_destination", "type": "String, Symbol", "description": "LEFT or RIGHT"}], "returns": {"type": "nil, String", "description": "the element, or nil when the source key does not exist"}}],
    "BLMOVE": [{"signature": "blmove(source, destination, where_source, where_destination, timeout: 0)", "params": [{"name": "source", "type": "String", "description": "source key"}, {"name": "destination", "type": "String", "description": "destination key"}, {"name": "where_source", "type": "String, Symbol", "description": "LEFT or RIGHT"}, {"name": "where_destination", "type": "String, Symbol", "description": "LEFT or RIGHT"}, {"name": "timeout", "type": "Float, Integer", "description": "timeout in seconds"}], "returns": {"type": "nil, String", "description": "the element, or nil when the source key does not exist or the timeout expired"}}],
    "LPUSH": [{"signature": "lpush(key, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "value", "type": "String, Array<String>", "description": "string value, or array of string values to push"}], "returns": {"type": "Integer", "description": "the length of the list after the push operation"}}],
    "LPUSHX": [{"signature": "lpushx(key, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "value", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "the length of the list after the push operation"}}],
    "RPUSH": [{"signature": "rpush(key, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "value", "type": "String, Array<String>", "description": "string value, or array of string values to push"}], "returns": {"type": "Integer", "description": "the length of the list after the push operation"}}],
    "RPUSHX": [{"signature": "rpushx(key, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "value", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "the length of the list after the push operation"}}],
    "LPOP": [{"signature": "lpop(key, count = nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "count", "type": "Integer", "description": "number of elements to remove"}], "returns": {"type": "nil, String, Array<String>", "description": "the values of the first elements"}}],
    "RPOP": [{"signature": "rpop(key, count = nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "count", "type": "Integer", "description": "number of elements to remove"}], "returns": {"type": "nil, String, Array<String>", "description": "the values of the last elements"}}],
    "RPOPLPUSH": [{"signature": "rpoplpush(source, destination)", "params": [{"name": "source", "type": "String", "description": "source key"}, {"name": "destination", "type": "String", "description": "destination key"}], "returns": {"type": "nil, String", "description": "the element, or nil when the source key does not exist"}}],
    "BLPOP": [{"signature": "blpop(*args)", "params": [{"name": "*args", "type": "String, Array<String>", "description": "one or more keys to perform the blocking pop on"}, {"name": "timeout", "type": "Float, Integer", "description": "timeout in seconds"}], "returns": {"type": "nil, [String, String]", "description": "tuple of the list that was popped from and element"}}],
    "BRPOP": [{"signature": "brpop(*args)", "params": [{"name": "*args", "type": "String, Array<String>", "description": "one or more keys to perform the blocking pop on"}, {"name": "timeout", "type": "Float, Integer", "description": "timeout in seconds"}], "returns": {"type": "nil, [String, String]", "description": "tuple of the list that was popped from and element"}}],
    "BRPOPLPUSH": [{"signature": "brpoplpush(source, destination, timeout: 0)", "params": [{"name": "source", "type": "String", "description": "source key"}, {"name": "destination", "type": "String", "description": "destination key"}, {"name": "timeout", "type": "Float, Integer", "description": "timeout in seconds"}], "returns": {"type": "nil, String", "description": "the element was popped and pushed"}}],
    "BLMPOP": [{"signature": "blmpop(timeout, *keys, modifier: \"LEFT\", count: nil)", "params": [{"name": "timeout", "type": "Float", "description": "maximum number of seconds to block"}, {"name": "*keys", "type": "String, Array<String>", "description": "one or more keys with lists"}, {"name": "modifier", "type": "String", "description": "LEFT or RIGHT"}, {"name": "count", "type": "Integer", "description": "a number of elements to pop"}], "returns": {"type": "Array<String, Array<String>>", "description": "list of popped elements or nil"}}],
    "LMPOP": [{"signature": "lmpop(*keys, modifier: \"LEFT\", count: nil)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": "one or more keys with lists"}, {"name": "modifier", "type": "String", "description": "LEFT or RIGHT"}, {"name": "count", "type": "Integer", "description": "a number of elements to pop"}], "returns": {"type": "Array<String, Array<String>>", "description": "list of popped elements or nil"}}],
    "LINDEX": [{"signature": "lindex(key, index)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "index", "type": "Integer", "description": ""}], "returns": {"type": "String", "description": ""}}],
    "LINSERT": [{"signature": "linsert(key, where, pivot, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "where", "type": "String, Symbol", "description": "BEFORE or AFTER"}, {"name": "pivot", "type": "String", "description": "reference element"}, {"name": "value", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "length of the list after the insert operation, or -1 when the element pivot was not found"}}],
    "LRANGE": [{"signature": "lrange(key, start, stop)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "start", "type": "Integer", "description": "start index"}, {"name": "stop", "type": "Integer", "description": "stop index"}], "returns": {"type": "Array<String>", "description": ""}}],
    "LREM": [{"signature": "lrem(key, count, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "count", "type": "Integer", "description": "number of elements to remove"}, {"name": "value", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "the number of removed elements"}}],
    "LSET": [{"signature": "lset(key, index, value)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "index", "type": "Integer", "description": ""}, {"name": "value", "type": "String", "description": ""}], "returns": {"type": "String", "description": "OK"}}],
    "LTRIM": [{"signature": "ltrim(key, start, stop)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "start", "type": "Integer", "description": "start index"}, {"name": "stop", "type": "Integer", "description": "stop index"}], "returns": {"type": "String", "description": "OK"}}],

    # === SETS ===
    "SCARD": [{"signature": "scard(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": ""}}],
    "SADD": [{"signature": "sadd(key, *members)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*members", "type": "String, Array<String>", "description": "one member, or array of members"}], "returns": {"type": "Integer", "description": "The number of members that were successfully added"}}],
    "SREM": [{"signature": "srem(key, *members)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*members", "type": "String, Array<String>", "description": "one member, or array of members"}], "returns": {"type": "Integer", "description": "The number of members that were successfully removed"}}],
    "SPOP": [{"signature": "spop(key, count = nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "count", "type": "Integer", "description": ""}], "returns": {"type": "String", "description": ""}}],
    "SRANDMEMBER": [{"signature": "srandmember(key, count = nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "count", "type": "Integer", "description": ""}], "returns": {"type": "String", "description": ""}}],
    "SMOVE": [{"signature": "smove(source, destination, member)", "params": [{"name": "source", "type": "String", "description": "source key"}, {"name": "destination", "type": "String", "description": "destination key"}, {"name": "member", "type": "String", "description": "member to move from source to destination"}], "returns": {"type": "Boolean", "description": ""}}],
    "SISMEMBER": [{"signature": "sismember(key, member)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "member", "type": "String", "description": ""}], "returns": {"type": "Boolean", "description": ""}}],
    "SMISMEMBER": [{"signature": "smismember(key, *members)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*members", "type": "String, Array<String>", "description": ""}], "returns": {"type": "Array<Boolean>", "description": ""}}],
    "SMEMBERS": [{"signature": "smembers(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Array<String>", "description": ""}}],
    "SDIFF": [{"signature": "sdiff(*keys)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": "keys pointing to sets to subtract"}], "returns": {"type": "Array<String>", "description": "members in the difference"}}],
    "SDIFFSTORE": [{"signature": "sdiffstore(destination, *keys)", "params": [{"name": "destination", "type": "String", "description": "destination key"}, {"name": "*keys", "type": "String, Array<String>", "description": "keys pointing to sets to subtract"}], "returns": {"type": "Integer", "description": "number of elements in the resulting set"}}],
    "SINTER": [{"signature": "sinter(*keys)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": "keys pointing to sets to intersect"}], "returns": {"type": "Array<String>", "description": "members in the intersection"}}],
    "SINTERSTORE": [{"signature": "sinterstore(destination, *keys)", "params": [{"name": "destination", "type": "String", "description": "destination key"}, {"name": "*keys", "type": "String, Array<String>", "description": "keys pointing to sets to intersect"}], "returns": {"type": "Integer", "description": "number of elements in the resulting set"}}],
    "SUNION": [{"signature": "sunion(*keys)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": "keys pointing to sets to unify"}], "returns": {"type": "Array<String>", "description": "members in the union"}}],
    "SUNIONSTORE": [{"signature": "sunionstore(destination, *keys)", "params": [{"name": "destination", "type": "String", "description": "destination key"}, {"name": "*keys", "type": "String, Array<String>", "description": "keys pointing to sets to unify"}], "returns": {"type": "Integer", "description": "number of elements in the resulting set"}}],
    "SSCAN": [{"signature": "sscan(key, cursor, **options)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "cursor", "type": "String, Integer", "description": "the cursor of the iteration"}, {"name": "match", "type": "String", "description": "only return keys matching the pattern"}, {"name": "count", "type": "Integer", "description": "return count keys at most per iteration"}], "returns": {"type": "Array", "description": "the next cursor and all found members"}}],

    # === SORTED SETS ===
    "ZCARD": [{"signature": "zcard(key)", "params": [{"name": "key", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": ""}}],
    "ZADD": [{"signature": "zadd(key, *args, nx: nil, xx: nil, lt: nil, gt: nil, ch: nil, incr: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*args", "type": "[Float, String], Array<[Float, String]>", "description": "a single [score, member] pair or an array of pairs"}, {"name": "nx", "type": "Boolean", "description": "Only add elements that do not already exist"}, {"name": "xx", "type": "Boolean", "description": "Only update elements that already exist"}, {"name": "lt", "type": "Boolean", "description": "Only update existing elements if the new score is less than the current score"}, {"name": "gt", "type": "Boolean", "description": "Only update existing elements if the new score is greater than the current score"}, {"name": "ch", "type": "Boolean", "description": "Return the total number of elements changed"}, {"name": "incr", "type": "Boolean", "description": "ZADD acts like ZINCRBY"}], "returns": {"type": "Boolean, Integer, Float", "description": ""}}],
    "ZINCRBY": [{"signature": "zincrby(key, increment, member)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "increment", "type": "Float", "description": ""}, {"name": "member", "type": "String", "description": ""}], "returns": {"type": "Float", "description": "score of the member after incrementing it"}}],
    "ZREM": [{"signature": "zrem(key, member)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "member", "type": "String, Array<String>", "description": "a single member or an array of members"}], "returns": {"type": "Boolean, Integer", "description": ""}}],
    "ZPOPMAX": [{"signature": "zpopmax(key, count = nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "count", "type": "Integer", "description": "a number of members"}], "returns": {"type": "Array<String, Float>, Array<Array<String, Float>>", "description": "element and score pair"}}],
    "ZPOPMIN": [{"signature": "zpopmin(key, count = nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "count", "type": "Integer", "description": "a number of members"}], "returns": {"type": "Array<String, Float>, Array<Array<String, Float>>", "description": "element and score pair"}}],
    "BZMPOP": [{"signature": "bzmpop(timeout, *keys, modifier: \"MIN\", count: nil)", "params": [{"name": "timeout", "type": "Float", "description": "maximum number of seconds to block"}, {"name": "*keys", "type": "String, Array<String>", "description": "one or more keys with sorted sets"}, {"name": "modifier", "type": "String", "description": "MIN or MAX"}, {"name": "count", "type": "Integer", "description": "a number of members to pop"}], "returns": {"type": "Array<String, Array<String, Float>>", "description": "list of popped elements and scores"}}],
    "ZMPOP": [{"signature": "zmpop(*keys, modifier: \"MIN\", count: nil)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": "one or more keys with sorted sets"}, {"name": "modifier", "type": "String", "description": "MIN or MAX"}, {"name": "count", "type": "Integer", "description": "a number of members to pop"}], "returns": {"type": "Array<String, Array<String, Float>>", "description": "list of popped elements and scores"}}],
    "BZPOPMAX": [{"signature": "bzpopmax(*args)", "params": [{"name": "*args", "type": "Array<String>", "description": "one or multiple keys of the sorted sets"}, {"name": "timeout", "type": "Integer", "description": "the maximum number of seconds to block"}], "returns": {"type": "Array<String, String, Float>", "description": "a tuple of key, member and score"}}],
    "BZPOPMIN": [{"signature": "bzpopmin(*args)", "params": [{"name": "*args", "type": "Array<String>", "description": "one or multiple keys of the sorted sets"}, {"name": "timeout", "type": "Integer", "description": "the maximum number of seconds to block"}], "returns": {"type": "Array<String, String, Float>", "description": "a tuple of key, member and score"}}],
    "ZSCORE": [{"signature": "zscore(key, member)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "member", "type": "String", "description": ""}], "returns": {"type": "Float", "description": "score of the member"}}],
    "ZMSCORE": [{"signature": "zmscore(key, *members)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*members", "type": "String, Array<String>", "description": ""}], "returns": {"type": "Array<Float>", "description": "scores of the members"}}],
    "ZRANDMEMBER": [{"signature": "zrandmember(key, count = nil, with_scores: false)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "count", "type": "Integer", "description": ""}, {"name": "with_scores", "type": "Boolean", "description": "include scores in output"}], "returns": {"type": "nil, String, Array<String>, Array<[String, Float]>", "description": ""}}],
    "ZRANGE": [{"signature": "zrange(key, start, stop, by_score: false, by_lex: false, rev: false, limit: nil, with_scores: false)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "start", "type": "Integer", "description": "start index"}, {"name": "stop", "type": "Integer", "description": "stop index"}, {"name": "by_score", "type": "Boolean", "description": "return members by score"}, {"name": "by_lex", "type": "Boolean", "description": "return members by lexicographical ordering"}, {"name": "rev", "type": "Boolean", "description": "reverse the ordering"}, {"name": "limit", "type": "Array", "description": "[offset, count]"}, {"name": "with_scores", "type": "Boolean", "description": "include scores in output"}], "returns": {"type": "Array<String>, Array<[String, Float]>", "description": ""}}],
    "ZRANGESTORE": [{"signature": "zrangestore(dest_key, src_key, start, stop, by_score: false, by_lex: false, rev: false, limit: nil)", "params": [{"name": "dest_key", "type": "String", "description": "destination key"}, {"name": "src_key", "type": "String", "description": "source key"}, {"name": "start", "type": "Integer", "description": "start index"}, {"name": "stop", "type": "Integer", "description": "stop index"}, {"name": "by_score", "type": "Boolean", "description": "return members by score"}, {"name": "by_lex", "type": "Boolean", "description": "return members by lexicographical ordering"}, {"name": "rev", "type": "Boolean", "description": "reverse the ordering"}, {"name": "limit", "type": "Array", "description": "[offset, count]"}], "returns": {"type": "Integer", "description": "the number of elements in the resulting sorted set"}}],
    "ZREVRANGE": [{"signature": "zrevrange(key, start, stop, with_scores: false)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "start", "type": "Integer", "description": ""}, {"name": "stop", "type": "Integer", "description": ""}, {"name": "with_scores", "type": "Boolean", "description": "include scores in output"}], "returns": {"type": "Array<String>, Array<[String, Float]>", "description": ""}}],
    "ZRANK": [{"signature": "zrank(key, member, with_score: false)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "member", "type": "String", "description": ""}, {"name": "with_score", "type": "Boolean", "description": "include score in output"}], "returns": {"type": "Integer, [Integer, Float]", "description": ""}}],
    "ZREVRANK": [{"signature": "zrevrank(key, member, with_score: false)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "member", "type": "String", "description": ""}, {"name": "with_score", "type": "Boolean", "description": "include score in output"}], "returns": {"type": "Integer, [Integer, Float]", "description": ""}}],
    "ZREMRANGEBYRANK": [{"signature": "zremrangebyrank(key, start, stop)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "start", "type": "Integer", "description": "start index"}, {"name": "stop", "type": "Integer", "description": "stop index"}], "returns": {"type": "Integer", "description": "number of members that were removed"}}],
    "ZLEXCOUNT": [{"signature": "zlexcount(key, min, max)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "min", "type": "String", "description": ""}, {"name": "max", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "number of members within the specified lexicographical range"}}],
    "ZRANGEBYLEX": [{"signature": "zrangebylex(key, min, max, limit: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "min", "type": "String", "description": ""}, {"name": "max", "type": "String", "description": ""}, {"name": "limit", "type": "Array", "description": "[offset, count]"}], "returns": {"type": "Array<String>", "description": ""}}],
    "ZREVRANGEBYLEX": [{"signature": "zrevrangebylex(key, max, min, limit: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "max", "type": "String", "description": ""}, {"name": "min", "type": "String", "description": ""}, {"name": "limit", "type": "Array", "description": "[offset, count]"}], "returns": {"type": "Array<String>", "description": ""}}],
    "ZRANGEBYSCORE": [{"signature": "zrangebyscore(key, min, max, with_scores: false, limit: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "min", "type": "String", "description": ""}, {"name": "max", "type": "String", "description": ""}, {"name": "with_scores", "type": "Boolean", "description": "include scores in output"}, {"name": "limit", "type": "Array", "description": "[offset, count]"}], "returns": {"type": "Array<String>, Array<[String, Float]>", "description": ""}}],
    "ZREVRANGEBYSCORE": [{"signature": "zrevrangebyscore(key, max, min, with_scores: false, limit: nil)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "max", "type": "String", "description": ""}, {"name": "min", "type": "String", "description": ""}, {"name": "with_scores", "type": "Boolean", "description": "include scores in output"}, {"name": "limit", "type": "Array", "description": "[offset, count]"}], "returns": {"type": "Array<String>, Array<[String, Float]>", "description": ""}}],
    "ZREMRANGEBYSCORE": [{"signature": "zremrangebyscore(key, min, max)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "min", "type": "String", "description": ""}, {"name": "max", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "number of members that were removed"}}],
    "ZCOUNT": [{"signature": "zcount(key, min, max)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "min", "type": "String", "description": ""}, {"name": "max", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "number of members within the specified range"}}],
    "ZINTER": [{"signature": "zinter(*keys, weights: nil, aggregate: nil, with_scores: false)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": "one or more keys to intersect"}, {"name": "weights", "type": "Array<Float>", "description": "weights to associate with source sorted sets"}, {"name": "aggregate", "type": "String", "description": "aggregate function to use (sum, min, max)"}, {"name": "with_scores", "type": "Boolean", "description": "include scores in output"}], "returns": {"type": "Array<String>, Array<[String, Float]>", "description": ""}}],
    "ZINTERSTORE": [{"signature": "zinterstore(destination, keys, weights: nil, aggregate: nil)", "params": [{"name": "destination", "type": "String", "description": "destination key"}, {"name": "keys", "type": "Array<String>", "description": "source keys"}, {"name": "weights", "type": "Array<Float>", "description": "weights to associate with source sorted sets"}, {"name": "aggregate", "type": "String", "description": "aggregate function to use (sum, min, max)"}], "returns": {"type": "Integer", "description": "number of elements in the resulting sorted set"}}],
    "ZUNION": [{"signature": "zunion(*keys, weights: nil, aggregate: nil, with_scores: false)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": "one or more keys to union"}, {"name": "weights", "type": "Array<Float>", "description": "weights to associate with source sorted sets"}, {"name": "aggregate", "type": "String", "description": "aggregate function to use (sum, min, max)"}, {"name": "with_scores", "type": "Boolean", "description": "include scores in output"}], "returns": {"type": "Array<String>, Array<[String, Float]>", "description": ""}}],
    "ZUNIONSTORE": [{"signature": "zunionstore(destination, keys, weights: nil, aggregate: nil)", "params": [{"name": "destination", "type": "String", "description": "destination key"}, {"name": "keys", "type": "Array<String>", "description": "source keys"}, {"name": "weights", "type": "Array<Float>", "description": "weights to associate with source sorted sets"}, {"name": "aggregate", "type": "String", "description": "aggregate function to use (sum, min, max)"}], "returns": {"type": "Integer", "description": "number of elements in the resulting sorted set"}}],
    "ZDIFF": [{"signature": "zdiff(*keys, with_scores: false)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": "one or more keys to compute the difference"}, {"name": "with_scores", "type": "Boolean", "description": "include scores in output"}], "returns": {"type": "Array<String>, Array<[String, Float]>", "description": ""}}],
    "ZDIFFSTORE": [{"signature": "zdiffstore(destination, keys)", "params": [{"name": "destination", "type": "String", "description": "destination key"}, {"name": "keys", "type": "Array<String>", "description": "source keys"}], "returns": {"type": "Integer", "description": "number of elements in the resulting sorted set"}}],
    "ZSCAN": [{"signature": "zscan(key, cursor, **options)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "cursor", "type": "String, Integer", "description": "the cursor of the iteration"}, {"name": "match", "type": "String", "description": "only return keys matching the pattern"}, {"name": "count", "type": "Integer", "description": "return count keys at most per iteration"}], "returns": {"type": "Array", "description": "the next cursor and all found members and scores"}}],

    # === STREAMS ===
    "XINFO": [{"signature": "xinfo(subcommand, key, group = nil)", "params": [{"name": "subcommand", "type": "String", "description": "stream, groups, or consumers"}, {"name": "key", "type": "String", "description": "the stream key"}, {"name": "group", "type": "String", "description": "the consumer group name, required if subcommand is consumers"}], "returns": {"type": "Hash, Array<Hash>", "description": "information of the stream or consumer groups"}}],
    "XADD": [{"signature": "xadd(key, entry, approximate: nil, maxlen: nil, minid: nil, nomkstream: nil, id: '*')", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "entry", "type": "Hash", "description": "one or multiple field-value pairs"}, {"name": "approximate", "type": "Boolean", "description": "whether to add ~ modifier of maxlen/minid or not"}, {"name": "maxlen", "type": "Integer", "description": "max length of entries to keep"}, {"name": "minid", "type": "Integer", "description": "min id of entries to keep"}, {"name": "nomkstream", "type": "Boolean", "description": "whether to add NOMKSTREAM"}, {"name": "id", "type": "String", "description": "the entry id, default value is *"}], "returns": {"type": "String", "description": "the entry id"}}],
    "XTRIM": [{"signature": "xtrim(key, len_or_id, strategy: 'MAXLEN', approximate: false, limit: nil)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "len_or_id", "type": "Integer, String", "description": "max length or minimum id"}, {"name": "strategy", "type": "String", "description": "MAXLEN or MINID"}, {"name": "approximate", "type": "Boolean", "description": "whether to add ~ modifier"}, {"name": "limit", "type": "Integer", "description": "maximum count of entries to be evicted"}], "returns": {"type": "Integer", "description": "the number of entries actually deleted"}}],
    "XDEL": [{"signature": "xdel(key, *ids)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "*ids", "type": "Array<String>", "description": "one or multiple entry ids"}], "returns": {"type": "Integer", "description": "the number of entries actually deleted"}}],
    "XRANGE": [{"signature": "xrange(key, start = '-', range_end = '+', count: nil)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "start", "type": "String", "description": "first entry id of range, default is -"}, {"name": "range_end", "type": "String", "description": "last entry id of range, default is +"}, {"name": "count", "type": "Integer", "description": "the number of entries as limit"}], "returns": {"type": "Array<Array<String, Hash>>", "description": "the ids and entries pairs"}}],
    "XREVRANGE": [{"signature": "xrevrange(key, range_end = '+', start = '-', count: nil)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "range_end", "type": "String", "description": "first entry id of range, default is +"}, {"name": "start", "type": "String", "description": "last entry id of range, default is -"}, {"name": "count", "type": "Integer", "description": "the number of entries as limit"}], "returns": {"type": "Array<Array<String, Hash>>", "description": "the ids and entries pairs"}}],
    "XLEN": [{"signature": "xlen(key)", "params": [{"name": "key", "type": "String", "description": "the stream key"}], "returns": {"type": "Integer", "description": "the number of entries"}}],
    "XREAD": [{"signature": "xread(keys, ids, count: nil, block: nil)", "params": [{"name": "keys", "type": "Array<String>", "description": "one or multiple stream keys"}, {"name": "ids", "type": "Array<String>", "description": "one or multiple entry ids"}, {"name": "count", "type": "Integer", "description": "the number of entries as limit per stream"}, {"name": "block", "type": "Integer", "description": "the number of milliseconds as blocking timeout"}], "returns": {"type": "Hash", "description": "the entries"}}],
    "XGROUP CREATE": [{"signature": "xgroup(:create, key, group, id_or_consumer, mkstream: false)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "group", "type": "String", "description": "the consumer group name"}, {"name": "id_or_consumer", "type": "String", "description": "the entry id or $"}, {"name": "mkstream", "type": "Boolean", "description": "whether to create an empty stream automatically or not"}], "returns": {"type": "String", "description": "OK"}}],
    "XGROUP SETID": [{"signature": "xgroup(:setid, key, group, id_or_consumer)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "group", "type": "String", "description": "the consumer group name"}, {"name": "id_or_consumer", "type": "String", "description": "the entry id or $"}], "returns": {"type": "String", "description": "OK"}}],
    "XGROUP DESTROY": [{"signature": "xgroup(:destroy, key, group)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "group", "type": "String", "description": "the consumer group name"}], "returns": {"type": "Integer", "description": "effected count"}}],
    "XGROUP DELCONSUMER": [{"signature": "xgroup(:delconsumer, key, group, consumer)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "group", "type": "String", "description": "the consumer group name"}, {"name": "consumer", "type": "String", "description": "the consumer name"}], "returns": {"type": "Integer", "description": "effected count"}}],
    "XREADGROUP": [{"signature": "xreadgroup(group, consumer, keys, ids, count: nil, block: nil, noack: nil)", "params": [{"name": "group", "type": "String", "description": "the consumer group name"}, {"name": "consumer", "type": "String", "description": "the consumer name"}, {"name": "keys", "type": "Array<String>", "description": "one or multiple stream keys"}, {"name": "ids", "type": "Array<String>", "description": "one or multiple entry ids"}, {"name": "count", "type": "Integer", "description": "the number of entries as limit"}, {"name": "block", "type": "Integer", "description": "the number of milliseconds as blocking timeout"}, {"name": "noack", "type": "Boolean", "description": "whether message loss is acceptable or not"}], "returns": {"type": "Hash", "description": "the entries"}}],
    "XACK": [{"signature": "xack(key, group, *ids)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "group", "type": "String", "description": "the consumer group name"}, {"name": "*ids", "type": "Array<String>", "description": "one or multiple entry ids"}], "returns": {"type": "Integer", "description": "the number of entries successfully acknowledged"}}],
    "XCLAIM": [{"signature": "xclaim(key, group, consumer, min_idle_time, *ids, **opts)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "group", "type": "String", "description": "the consumer group name"}, {"name": "consumer", "type": "String", "description": "the consumer name"}, {"name": "min_idle_time", "type": "Integer", "description": "the number of milliseconds"}, {"name": "*ids", "type": "Array<String>", "description": "one or multiple entry ids"}, {"name": "idle", "type": "Integer", "description": "the number of milliseconds as last time it was delivered"}, {"name": "time", "type": "Integer", "description": "the number of milliseconds as a specific Unix Epoch time"}, {"name": "retrycount", "type": "Integer", "description": "the number of retry counter"}, {"name": "force", "type": "Boolean", "description": "whether to create the pending entry"}, {"name": "justid", "type": "Boolean", "description": "whether to fetch just an array of entry ids"}], "returns": {"type": "Hash, Array<String>", "description": "the entries successfully claimed"}}],
    "XAUTOCLAIM": [{"signature": "xautoclaim(key, group, consumer, min_idle_time, start, count: nil, justid: false)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "group", "type": "String", "description": "the consumer group name"}, {"name": "consumer", "type": "String", "description": "the consumer name"}, {"name": "min_idle_time", "type": "Integer", "description": "the number of milliseconds"}, {"name": "start", "type": "String", "description": "entry id to start scanning from or 0-0 for everything"}, {"name": "count", "type": "Integer", "description": "number of messages to claim"}, {"name": "justid", "type": "Boolean", "description": "whether to fetch just an array of entry ids"}], "returns": {"type": "Hash, Array<String>", "description": "the entries successfully claimed"}}],
    "XPENDING": [{"signature": "xpending(key, group, *args, idle: nil)", "params": [{"name": "key", "type": "String", "description": "the stream key"}, {"name": "group", "type": "String", "description": "the consumer group name"}, {"name": "start", "type": "String", "description": "start first entry id of range"}, {"name": "end", "type": "String", "description": "end last entry id of range"}, {"name": "count", "type": "Integer", "description": "the number of entries as limit"}, {"name": "consumer", "type": "String", "description": "the consumer name"}, {"name": "idle", "type": "Integer", "description": "pending message minimum idle time in milliseconds"}], "returns": {"type": "Hash, Array<Hash>", "description": "the summary of pending entries or pending entries details"}}],

    # === GEO ===
    "GEOADD": [{"signature": "geoadd(key, *member)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "*member", "type": "Array", "description": "longitude, latitude, name"}], "returns": {"type": "Integer", "description": "number of elements added to the sorted set"}}],
    "GEOHASH": [{"signature": "geohash(key, member)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "member", "type": "String, Array<String>", "description": "one member or array of members"}], "returns": {"type": "Array<String, nil>", "description": "array containing geohash string if member is present, nil otherwise"}}],
    "GEORADIUS": [{"signature": "georadius(*args, **geoptions)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "longitude", "type": "Float", "description": ""}, {"name": "latitude", "type": "Float", "description": ""}, {"name": "radius", "type": "Float", "description": ""}, {"name": "unit", "type": "String", "description": "m|km|ft|mi"}, {"name": "sort", "type": "String", "description": "asc or desc"}, {"name": "count", "type": "Integer", "description": "limit the results"}, {"name": "options", "type": "String", "description": "WITHDIST, WITHCOORD, WITHHASH"}], "returns": {"type": "Array<String>", "description": ""}}],
    "GEORADIUSBYMEMBER": [{"signature": "georadiusbymember(*args, **geoptions)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "member", "type": "String", "description": ""}, {"name": "radius", "type": "Float", "description": ""}, {"name": "unit", "type": "String", "description": "m|km|ft|mi"}, {"name": "sort", "type": "String", "description": "asc or desc"}, {"name": "count", "type": "Integer", "description": "limit the results"}, {"name": "options", "type": "String", "description": "WITHDIST, WITHCOORD, WITHHASH"}], "returns": {"type": "Array<String>", "description": ""}}],
    "GEOPOS": [{"signature": "geopos(key, member)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "member", "type": "String, Array<String>", "description": "one member or array of members"}], "returns": {"type": "Array<Array<String>, nil>", "description": "array of elements, where each element is either array of longitude and latitude or nil"}}],
    "GEODIST": [{"signature": "geodist(key, member1, member2, unit = 'm')", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "member1", "type": "String", "description": ""}, {"name": "member2", "type": "String", "description": ""}, {"name": "unit", "type": "String", "description": "m, km, mi, ft"}], "returns": {"type": "String, nil", "description": "distance in specified unit if both members present, nil otherwise"}}],

    # === HYPERLOGLOG ===
    "PFADD": [{"signature": "pfadd(key, member)", "params": [{"name": "key", "type": "String", "description": ""}, {"name": "member", "type": "String, Array<String>", "description": "one member, or array of members"}], "returns": {"type": "Boolean", "description": "true if at least 1 HyperLogLog internal register was altered"}}],
    "PFCOUNT": [{"signature": "pfcount(*keys)", "params": [{"name": "*keys", "type": "String, Array<String>", "description": ""}], "returns": {"type": "Integer", "description": ""}}],
    "PFMERGE": [{"signature": "pfmerge(dest_key, *source_key)", "params": [{"name": "dest_key", "type": "String", "description": "destination key"}, {"name": "*source_key", "type": "String, Array<String>", "description": "source key, or array of keys"}], "returns": {"type": "Boolean", "description": ""}}],

    # === PUB/SUB ===
    "PUBLISH": [{"signature": "publish(channel, message)", "params": [{"name": "channel", "type": "String", "description": ""}, {"name": "message", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "number of clients that received the message"}}],
    "SUBSCRIBE": [{"signature": "subscribe(*channels, &block)", "params": [{"name": "*channels", "type": "Array<String>", "description": ""}], "returns": {"type": "nil", "description": ""}}],
    "UNSUBSCRIBE": [{"signature": "unsubscribe(*channels)", "params": [{"name": "*channels", "type": "Array<String>", "description": ""}], "returns": {"type": "nil", "description": ""}}],
    "PSUBSCRIBE": [{"signature": "psubscribe(*channels, &block)", "params": [{"name": "*channels", "type": "Array<String>", "description": ""}], "returns": {"type": "nil", "description": ""}}],
    "PUNSUBSCRIBE": [{"signature": "punsubscribe(*channels)", "params": [{"name": "*channels", "type": "Array<String>", "description": ""}], "returns": {"type": "nil", "description": ""}}],
    "PUBSUB": [{"signature": "pubsub(subcommand, *args)", "params": [{"name": "subcommand", "type": "String", "description": "channels, numsub, numpat"}, {"name": "*args", "type": "Array", "description": ""}], "returns": {"type": "Array, Integer", "description": ""}}],
    "SPUBLISH": [{"signature": "spublish(channel, message)", "params": [{"name": "channel", "type": "String", "description": ""}, {"name": "message", "type": "String", "description": ""}], "returns": {"type": "Integer", "description": "number of clients that received the message"}}],
    "SSUBSCRIBE": [{"signature": "ssubscribe(*channels, &block)", "params": [{"name": "*channels", "type": "Array<String>", "description": ""}], "returns": {"type": "nil", "description": ""}}],
    "SUNSUBSCRIBE": [{"signature": "sunsubscribe(*channels)", "params": [{"name": "*channels", "type": "Array<String>", "description": ""}], "returns": {"type": "nil", "description": ""}}],
}

def update_json_file(filepath, mappings):
    """Add redis_rb mapping to a JSON file if a mapping exists."""
    command_name = Path(filepath).stem  # e.g., "GET" from "GET.json"
    
    if command_name not in mappings:
        return False
    
    with open(filepath, 'r') as f:
        data = json.load(f)
    
    if 'api_calls' not in data:
        return False
    
    # Skip if redis_rb already exists
    if 'redis_rb' in data['api_calls']:
        return False
    
    data['api_calls']['redis_rb'] = mappings[command_name]
    
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2)
        f.write('\n')
    
    return True

def main():
    mapping_dir = Path('data/command-api-mapping')
    updated = 0
    skipped = 0
    
    for json_file in sorted(mapping_dir.glob('*.json')):
        if update_json_file(json_file, REDIS_RB_MAPPINGS):
            print(f"Updated: {json_file.name}")
            updated += 1
        else:
            skipped += 1
    
    print(f"\nDone! Updated {updated} files, skipped {skipped} files.")

if __name__ == '__main__':
    main()

