{
 "title": "RDI Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "data_source", "label": "data_source", "query": { "query": "rdi_stream_event_latency_ms" } }
  ]
 },
 "panels": [
  {
   "title": "RDI Engine",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(rdi_engine_state)", "legendFormat": "Status" }
   ]
  },
  { "title": "Job data for $data_source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "data_source" },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdi_incoming_entries{operation=\"pending\", data_source=~\"$data_source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdi_incoming_entries{operation=\"updated\", data_source=~\"$data_source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdi_incoming_entries{operation=\"deleted\", data_source=~\"$data_source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inserted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdi_incoming_entries{operation=\"inserted\", data_source=~\"$data_source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdi_incoming_entries{operation=\"filtered\", data_source=~\"$data_source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdi_incoming_entries{operation=\"rejected\", data_source=~\"$data_source\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event latency",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rdi_stream_event_latency_ms{data_source=~\"$data_source\"}",
     "legendFormat": "{{data_source}}"
    }
   ]
  },
  {
   "title": "Ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "rate(rdi_incoming_entries{data_source=~\"$data_source\", operation!~\".*pending\"}[1m])",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}